# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-05-11 04:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('mobilePhone', models.IntegerField()),
                ('mail', models.EmailField(max_length=30)),
                ('addr', models.CharField(max_length=30)),
            ],
        ),
    ]
