# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-05-11 06:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emailClient', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emailaddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_ip', models.CharField(max_length=20)),
                ('user', models.CharField(max_length=200)),
                ('host', models.CharField(max_length=200)),
                ('pwd', models.CharField(max_length=200)),
                ('emailtype', models.CharField(max_length=20)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Emailcontent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('emailfrom', models.CharField(max_length=200)),
                ('emaildate', models.CharField(max_length=200)),
                ('content', models.TextField(max_length=2000)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_address', to='emailClient.Emailaddress')),
            ],
        ),
    ]
