# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-05-11 07:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailClient', '0002_emailaddress_emailcontent'),
    ]

    operations = [
        migrations.CreateModel(
            name='myEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('From', models.EmailField(max_length=30)),
                ('To', models.EmailField(max_length=30)),
                ('Subject', models.CharField(max_length=30)),
                ('Content', models.CharField(max_length=30)),
                ('Type', models.IntegerField()),
                ('DateTime', models.DateTimeField(verbose_name='time')),
            ],
        ),
    ]
