# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-05-11 15:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailClient', '0003_myemail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='mobilePhone',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='myemail',
            name='Content',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='myemail',
            name='DateTime',
            field=models.DateTimeField(auto_now=True, verbose_name='time'),
        ),
        migrations.AlterField(
            model_name='myemail',
            name='From',
            field=models.EmailField(max_length=200),
        ),
        migrations.AlterField(
            model_name='myemail',
            name='Subject',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='myemail',
            name='To',
            field=models.EmailField(max_length=200),
        ),
    ]
